website/auth.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from .models import User
from . import db
from flask_login import current_user, login_user, login_required, logout_user
from werkzeug.security import generate_password_hash, check_password_hash 

auth = Blueprint('auth', __name__)



@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        user = None

        # Check for empty inputs
        if (not username or not password):
            flash('Please enter your username and password.', category='error')
            return render_template("login.html", user=current_user)
       
        user = User.query.filter_by(username=username).first()
        if user:
            if check_password_hash(user.password, password):
                flash('You are now logged in!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home')) 
            else:
                flash('Wrong password.', category='error')
        else:
            flash('Username does not exist.', category='error')
            
    return render_template("login.html", user=current_user)



@auth.route('/logout')
@login_required 
def logout():
    logout_user()
    return redirect(url_for('auth.login'))



@auth.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        username = request.form['username']
        first_name = request.form['firstName']
        password1 = request.form['password1']
        password2 = request.form['password2']

        user = User.query.filter_by(username=username).first()
        if user:
            flash('Username exists already.', category='error')
        elif len(username) < 4:
            flash('Username must be greater than 3 characters.', category='error')
        elif len(first_name) < 2:
            flash('First Name must be greater than 1 character.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7 or len(password1) > 20:
            flash('Password must be between 7 and 20 characters long.', category='error')
        else: 
            new_user = User(username=username, \
                            first_name=first_name, \
                            password=generate_password_hash(password1))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('New account made! You are now logged in.', category='success')
            # after logging in, redirect User to the Home Page
            return redirect(url_for('views.home')) 

    return render_template("register.html", user=current_user)

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <!-- BOOTSTRAP 5.3.1 -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">

        <link 
            rel="icon" 
            href="data:image/svg+xml;utf8,
            <svg xmlns='http://www.w3.org/2000/svg' width='16' height='16' fill='green' class='bi bi-calendar-check' viewBox='0 0 16 16'><path d='M10.854 7.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L7.5 9.793l2.646-2.647a.5.5 0 0 1 .708 0z'/><path d='M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4H1z'/></svg>"
        >
        
        <!-- CUSTOM CSS -->
        <link type="text/css" rel="stylesheet" href="/static/style.css">

        <title>{% block title %} {% endblock %}</title>

    </head>

    <header>
        <nav class="navbar navbar-expand-lg navbar-container">
            <button
                class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbar"
            >
                <span class="nav-icon">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="white" class="bi bi-three-dots" viewBox="0 0 16 16">
                        <path d="M3 9.5a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3z"/>
                    </svg>
                </span>
            </button>

            <div class="collapse navbar-collapse" id="navbar">
                <div class="navbar-nav">
                    {% if user.is_authenticated %}
                        <a class="nav-item nav-link" id="home" href="/">Team Task Board</a>
                        <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
                    {% else %}
                        <a class="nav-item nav-link" id="login" href="/login">LOGIN</a>
                        <a class="nav-item nav-link" id="register" href="/register">REGISTER</a>
                    {% endif %}
                </div>
            </div>

            {% if user.is_authenticated %}
            <span class="title-header">
                <button class="btn" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasRight" aria-controls="offcanvasRight" style="background-color: rgba(0,0,0,0.7);">My Groups</button>
                <!--
                    <a href="/">My Groups</a>
                -->
            </span>
            {% else %}
            <span class="title-header">
                <a href="/">Team Task Board</a>
            </span>
            {% endif %}

        </nav>    

        <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel">
            <div class="offcanvas-header">
              <h5 class="offcanvas-title" id="offcanvasRightLabel">My Groups</h5>
              <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">
                <form method="POST">
                    <button class="btn canvas-link" type="submit" name="action" value="View All">All Groups</button>
                    {% for group in groups %}
                    <br>
                    <br>
                    <button class="btn canvas-link" type="submit" name="action" value={{ "Group" + group.id|string }}>{{group.name}}</button>
                    {% endfor %}
                </form>
            </div>
        </div>

    </header>

    <body>
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                {% if category == 'error' %}
                <!-- msg flashing for error messages ( 'alert-danger' )-->
                <div class="alert alert-danger alter-dismissable fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close btn-close" data-bs-dismiss="alert">
                    </button>
                </div>
                {% else %}
                <!-- msg flashing for success messages ( 'alert-danger' )-->
                <div class="alert alert-success alter-dismissable fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close btn-close" data-bs-dismiss="alert">
                    </button>
                </div>
                {% endif %}
            {% endfor %}
        {% endif %}
        {% endwith %}

        <!-- webpage content here -->
        <div class="container">
            {% block content %} {% endblock %}
        </div>

        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js" integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa" crossorigin="anonymous"></script>

        <!-- CUSTOM JAVASCRIPT -->
        <script src="../static/script.js"></script>
        
    </body>
</html>

website/templates/create-group.html
{% extends "base.html" %}

{% block title %} 
Team Task Board | Create New Group
{% endblock %}

{% block content %} 
<div class="content-section fade-container">
    <form class="card p-4 bg-light" method="POST">
        <legend class="main-header">Create New Group!</legend>

        <div class="form-group col-title">
            <label for="groupanme">Group Name</label>
            <input type="text" id="groupname" name="groupname" class="form-control" maxlength="30"/>
        </div>

        <div class="form-group row">
            <!-- ADD GROUP BTN -->
            <button type="submit" class="btn custom-btn col-md-4" name="action" value="New Group">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
                    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                    <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
                </svg>
                Add Group
            </button>
            <!-- RETURN HOME -->
            <button type="submit" class="btn custom-btn col-md-4" name="action" value="Return Home">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house-door-fill" viewBox="0 0 16 16">
                    <path d="M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5z"/>
                </svg>
                Return Home
            </button>
        </div>

    </form>
</div>
{% endblock %}

website/templates/create.html
{% extends "base.html" %}

{% block title %} 
Team Task Board| Editing Task
{% endblock %}

{% block content %} 
    <div class="content-section fade-container">
        <form class="card p-4 bg-light" method="POST">
            <legend class="main-header">Create New Task!</legend>

            <div class="form-group col-title">
                <label for="content">Task Details</label>
                <textarea id="content" name="content" class="form-control"></textarea>
            </div>

            <div class="row form-group">
                <div class="col col-md-6">
                    <label for="due_date" class="col-title">Due Date</label>
                    <br>
                    <input type="date" id="due_date" name="due_date">
                </div>
                
                <div class="col col-md-6">
                    <label for="time" class="col-title">Scheduled Time</label>
                    <br>
                    <input type="time" id="time" name="time">
                </div>
            </div>

            <div class="form-group row">
                <!-- ADD TASK BTN -->
                <button type="submit" class="btn custom-btn col-md-4" name="action" value="Add Task">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
                        <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                        <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
                    </svg>
                    Add Task
                </button>
                <!-- RETURN HOME -->
                <button type="submit" class="btn custom-btn col-md-4" name="action" value="Return Home">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house-door-fill" viewBox="0 0 16 16">
                        <path d="M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5z"/>
                    </svg>
                    Return Home
                </button>
            </div>
        </form>
    </div>

{% endblock %}

website/templates/login.html
{% extends "base.html" %}

{% block title %} Team Task Board | Login {% endblock %}

{% block content %} 
<br>
<br>
<div class="content-section fade-container">
    <form class="card p-4 bg-light" method="POST">
        <fieldset class="form-group"> 
            <legend class="main-header">Login</legend>
            <div class="form-group">
                <label for="username"> Username </label>
                <input type="text" class="form-control" id="username" name="username" placeholder="Enter username">
            </div>
            <div class="form-group">
                <label for="password"> Password </label>
                <input type="password" class="form-control" id="password" name="password" placeholder="Enter password">
            </div>
        </fieldset>
        <div class="form-group row">
            <button type="submit" class="btn col-sm-12 col-md-4 col-lg-3">Login</button>
        </div>
    </form>
    <br>
    <div class="bottom-form-div">
        <br>
        <span>
            Don't have an account?
            <a class="login-link" href="{{ url_for('auth.register') }}">Create Account!</a>
        </span>
    </div>
</div>
{% endblock %}

website/templates/register.html
{% extends "base.html" %}

{% block title %} Team Task Board | Sign Up {% endblock %}

{% block content %} 
<br>
<br>
<div class="content-section fade-container">
    <form class="card p-4 bg-light" method="POST">
        <fieldset class="form-group"> 
            <legend class="main-header">Join Today!</legend>
            <div class="form-group">
                <label for="username"> Username </label>
                <input type="text" class="form-control" id="username" name="username" placeholder="Enter username">
            </div>
            <div class="form-group"> 
                <label for="firstName"> First Name </label>
                <input type="text" class="form-control" id="firstName" name="firstName" placeholder="Enter first name">
            </div>
            <div class="form-group"> 
                <label for="password1"> Password </label>
                <small class="badge">Must be 7-20 characters long.</small>
                <input type="password" class="form-control" id="password1" name="password1" placeholder="Enter password">
            </div>
            <div class="form-group"> 
                <label for="password2"> Password (Confirm) </label>
                <input type="password" class="form-control" id="password2" name="password2" placeholder="Confirm password">
            </div>
        </fieldset>
        <div class="form-group row">
            <button type="submit" class="btn col-sm-12 col-md-4 col-lg-3">Register</button>
        </div>
    </form>
    <br>
    <div class="bottom-form-div">
        <br>
        <span>
            Already have an account?
            <a class="login-link" href="{{ url_for('auth.login') }}">Login</a>
        </span>
    </div>
</div>

{% endblock %}

website/templates/update.html
{% extends "base.html" %}

{% block title %} 
Team Task Board | Update Task
{% endblock %}

{% block content %} 
  <div class="content-section fade-container">
    <form class="card p-4 bg-light" method="POST">
      <legend class="main-header">Update Task Below</legend>

      <div class="form-group col-title">
        <div class="badge date-badge">Current Due Date</div>
        
        <div id="curr-due-date-text">
          {{task.due_date}}
          {% if task.time|length > 1%}
            at {{task.time}}
          {% endif %}
        </div>

      </div>

      <div class="form-group">
        <label for="content" class="col-title">Task Details</label>
        <textarea 
          id="content" 
          name="content" 
          class="form-control"
        >{{task.content}}</textarea>
      </div>

      <div class="row form-group">
        <div class="col col-lg-3">
          <label for="due_date" class="col-title">Due Date</label>
          <br>
          <input type="date" id="due_date" name="due_date" value="{{ task.due_date_int }}">
        </div>

        <div class="col col-lg-3">
          <label for="time" class="col-title">Time</label>
          <br>
          {% set format_time = task.time[:-3] %}
          {% if task.time[:-3]|length == 4 %}
            {# pad string with leading 0 #}
            {% set format_time = '0' + task.time[:-3] %}
          {% endif %}

          {% if ('12:' in task.time and 'AM' in task.time) %}
            {# check if 12AM #}
            {% set format_time = '00' + task.time[2:-3] %}
          {% elif '12:' not in task.time and 'PM' in task.time %}
            {# Add 12 to 1-11PM time, 12PM time remains unchanged #}
            {% set format_time = (((format_time[:2] | int) + 12) | string) + format_time[2:] %}
          {% endif %}

          <input type="time" id="time" name="time" value="{{ format_time }}">
        </div>

        <div class="col col-md-6 col-lg-3">
          <label for="status" class="col-title">Status</label>
          <br>
          <select name="taskStatus" aria-label="Select/Dropdown menu" id="curr_status">
            <option value="Cancelled">Cancelled</option>
            <option value="Not Yet Started" selected>Not Yet Started</option>
            <option value="In Progress">In Progress</option>
            <option value="Completed">Completed</option>
          </select>
        </div>

        <div class="col col-md-6 col-lg-3">
          <label for="group" class="col-title">Group</label>
          <br>
          <select name="groupSelect" aria-label="Group Dropdown" id="groupSelect">
            <option value="All" selected>All</option>
            {% for group in groups %}
            <option value={{group.id}}>{{group.name}}</option>
            {% endfor %}
          </select>
        </div>

      </div>

      <div class="form-group row">
        <!-- UPDATE -->
        <button type="submit" class="btn custom-btn col-md-4" name="action" value="Update">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-fill" viewBox="0 0 16 16">
            <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"/>
          </svg>
          Update
        </button>
        <!-- RETURN HOME -->
        <button type="submit" class="btn custom-btn col-md-4" name="action" value="Return Home">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house-door-fill" viewBox="0 0 16 16">
            <path d="M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5z"/>
          </svg>
          Return Home
        </button>
      </div>
    </form>
  </div>
{% endblock %}